name: Deploy Android app to Firebase App Distribution

on:
  workflow_dispatch:
    inputs:
      release_notes:
        description: 'Release Notes for the build'
        required: true
        default: 'Bug fixes and performance improvements.'
  workflow_call:
    inputs:
      release_notes:
        description: 'Release Notes for the build'
        required: true
        type: string

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3t
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Deploy to Firebase App Distribution
        uses: w9jds/firebase-action@master
        with:
          args: |
            appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app "1:482106246125:android:0903e179b7c0c4b033dde4" \
            --release-notes "${{ inputs.release_notes }}"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_APP_DISTRIBUTION_TOKEN }}
