name: Deploy Android app to Firebase App Distribution

on:
  workflow_dispatch:
    inputs:
      release_notes:
        description: 'Release Notes for the build'
        required: true
        default: 'Bug fixes and performance improvements.'
  workflow_call:
    inputs:
      release_notes:
        description: 'Release Notes for the build'
        required: true
        type: string

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Deploy to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: build/app/outputs/flutter-apk/app-release.apk
